### ISSUE TITLE
Change GUI/TUI dependencies to optional extras?

### ISSUE THREAD

**Issue by erezsh** [CZ-NIC/mininterface#3]
Installing the library comes with a lot of dependencies, for TUI and GUI support, that are not necessary for users who are only interested in CLI apps. Similarly, some might only want TUI or only GUI, and it's a shame to install more than necessary.

Installing unnecessary dependencies poses several drawbacks. They make installation time longer, and increase the chances of version conflicts, or installation errors.

It possible to specify these dependencies as "extras" to be installed with `pip install mininterface[tui]`, `mininterface[gui]` or `mininterface[all]`.

It's a small complication, but I think having a smaller footprint will make the project more attractive as a small utility library, that's easy to add to any project.

----

p.s. I used it for the first time today, and it was super easy and quick to set up a CLI. Kudos!

**Comment by e3rd** [comment]
Thanks! I've been crawling recently into the possibility to use `pip install mininterface[minimal]` but the installer seems to have no such option. Your suggestion seems to be the best option, I put this onto the roadmap.

**Comment by e3rd** [comment]
I've been thinking about this a lot and as I tend to keep the knowledge-requirement of the library the lowest possible, it seems to me the best to let the UI part be in the default installation. However, I've tested and added a section that describes how to install it with as little dependencies as possible – the library was ready for that as there existed an unused TextInterface that needs no dependency. https://github.com/CZ-NIC/mininterface?tab=readme-ov-file#minimal-installation

The minimal installation has 28 MB, the standard (with the nice TUI and GUI) 36 MB.

Second, I work on a lazy loading solution so that the dependencies are not cached to the memory on the program run if they are not used.

Does this seem reasonable for you?

**Comment by erezsh** [comment]
How would you do it from a pyproject.toml? or a requirements.txt file?

**Comment by e3rd** [comment]
Do you react on the first part (UI not installed) or to the second (if installed, UI not loaded)?

First part – On the link I've given, there is `--no-dependencies` flag that tells nothing is installed besides raw library. Then, the user has to install 3 required dependencies themself.  
This sounds to me great: by default, you do not bother with anything. But if the performance imports and you are willing to invest a little more time, you have to read a paragraph and run two installation lines instead of one. File `pyproject.toml` stays the same (and I think `requirements.txt` are deprecated in favour of `pyproject.toml`.)

Second part – The import is postponed to the moment the user actually uses the interface. Ex. if the first interface (GuiInterface) works, the second TuiInterface is not imported. (I'm doing tests on this right now.)

**Comment by e3rd** [comment]
An interesting finding. I've been working on the lazy loading. It seems that Python inner import methods are so advanced, it is not needed. Whether I used the default import statement or a lazy loader, the results were the same (or definitely < 0.01 ms).

Jupyter cell used for testing:

```python
%%timeit -n 200
from mininterface import run
from dataclasses import dataclass

@dataclass
class Env:
    test: str = "hello"
run(Env)
```

It takes `1.16 ms` to run. If `GuiInterface` is installed and used, it takes around 16 ms to initialize it.

[File](https://github.com/user-attachments/files/17569143/__init__.py.txt) used for testing attached. (Just change `LAZY = True` to turn on/off the lazy loading).

Hence, I do not plan to you the lazy loading features and willing to close the issue if you have no objection.

**Comment by erezsh** [comment]
What I meant is that `--no-dependencies` doesn't work inside pyproject.toml

So how can I include mininterface as a dependency, if I only want CLI features?

**Comment by e3rd** [comment]
You are right. I've been thinking about this on the weekend and I think you can stick with https://github.com/brentyi/tyro then. This is just the CLI library behind mininterface. You'll have just little more work with implementing config file.

Or do you see any benefits in using mininterface? The benefits of the mininterface is that it parses and asks for missing required fields for you etc but you want no UI.

I like a lot that you do not have to know anything and your app just works and forcing the users into specifying extras `[all]` would add a tiny step that they might have to debug.

**Comment by erezsh** [comment]
Another option you might consider is maintaining two pypi packages, `mininterface` and `mininterface-minimal`. It's a bit of an extra hassle, but If you use a script to publish them in tandem, I think it would be pretty minimal.

Thanks for the link, I'll check it out.

**Comment by erezsh** [comment]
P.S. feel free to close the issue if you decide against it.

**Comment by e3rd** [comment]
Thanks for another great idea. This might be the way to go. If you check the link and tell me a reason mininterface-minimal would still be useful over tyro, I'd try the tandem publishing!

**Comment by erezsh** [comment]
Honestly, tyro looks great. It even has support for sub-commands already.

Does mininterface have any features over tyro, expect for GUI/TUI?

**Comment by erezsh** [comment]
These all sound like nice features, but I can do well enough without them.

**Comment by e3rd** [comment]
Done then ;)

**Comment by e3rd** [comment]
For the reference, I've been previously wrong with not implementing the lazy loading. Now, I did:

* Mininterface = 1440 modules imported / 70 ms
* TextInterface = 1440 modules imported / 90 ms
* GuiInterface = 1463 modules imported / 130 ms
* TextualInterface = 1581 modules imported / 120 ms
* original state (both Gui+Tui) = 1603 modules / 175 ms

In the next release, we will save 50 ms of starting time then.

```python
%%timeit -n 1
from mininterface import run, Mininterface
from dataclasses import dataclass

@dataclass
class Env:
    test: str = "hello"
run(Env,interface="gui")  # or: "tui", Mininterface
# sys.modules.clear() would break the IDE testing
# if 'mininterface' in sys.modules:  # seems to not remove all the modules imported by the packages
    # del sys.modules['mininterface']
print(len(sys.modules))

# testing method
# As it is challenging to get just the import time, I've put print statements in the module being investigated,
# did one single test, summed the average with the worst case
# `76.8 ms ± 95.9 ms per loop` = 170 ms
# and restarted kernel to do few more attempts.
```
